In [1]:
from basic.utils.run.train import train
from basic.utils.common_utils import put_data_to_gpu
from basic.utils.run.train import Trainer
from basic.utils.vis_utils import VisualWindow
import easydict
import yaml
import torch
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

/home/ph/ENV/anaconda3/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(


In [2]:
top_cfg_path = '/home/ph/Desktop/PointCloud/utils_my/basic/model/model_cfg/second.yaml'
with open(top_cfg_path, 'rb') as f:
    top_cfg = easydict.EasyDict(yaml.load(f))
train_cfg = top_cfg.TRAIN_CONFIG

<ipython-input-2-f49754e0fb5e>:3: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  top_cfg = easydict.EasyDict(yaml.load(f))


# Train

In [3]:
# train(train_cfg)

# Inference

In [4]:
from basic.model.second import SECOND
from pathlib import Path
from kitti.kitti_dataset import get_dataloader

cfg_path = Path("../kitti/cfg/kitti_dataset.yaml")
dataloader = get_dataloader(data_cfg_path=cfg_path, class_name_list=['Car'], batch_size=2, training=True)
for data in dataloader:
    test_data = data
    break
test_data = put_data_to_gpu(test_data)
test_data

/home/ph/Desktop/PointCloud/utils_my/kitti/kitti_dataset.py:30: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = EasyDict(yaml.load(f))


{'frame_id': array(['006929', '006654'], dtype='<U6'),
 'gt_boxes': tensor([[[ 42.2162,  16.2627,  -0.6829,   3.6290,   1.6118,   1.5228,   0.3740,
             1.0000],
          [ 14.6838,   2.6501,  -0.8175,   4.0246,   1.5525,   1.4734,   0.3640,
             1.0000],
          [  5.1481,  -1.0924,  -0.8849,   3.7081,   1.5722,   1.5525,   0.3740,
             1.0000],
          [ 13.8693,  17.9889,  -1.2210,   3.8960,   1.4931,   1.5030,  -1.1660,
             1.0000],
          [ 11.9078,  23.1901,  -1.2504,   4.1927,   1.5426,   1.5624,  -1.2160,
             1.0000],
          [ 19.1566,   4.2201,  -0.8144,   3.5400,   1.4931,   1.5228,   0.3740,
             1.0000],
          [ 31.7228,   9.0921,  -0.7385,   3.8861,   1.5327,   1.4734,   0.3840,
             1.0000],
          [ 53.5898,  17.3070,  -0.4933,   4.0839,   1.6019,   1.7206,   0.3640,
             1.0000],
          [ 34.8650,  21.3092,  -0.8598,   4.1136,   1.5624,   1.4931,  -2.7460,
             1.0000],
      

In [5]:
%matplotlib auto
from basic.utils.run.train import Predictor
model_path = '/home/ph/Desktop/PointCloud/utils_my/basic/utils/run/check_point/2021-11-09::15:48:57/epoch29.pkl'
predictor = Predictor(model_path, class_names=['Car'])
# predictor = Predictor(model_path, class_names=['Car'], data_cfg_path=cfg_path, batch_size=2)
# predictor.predict_and_visualize()
preds_dict = predictor.predict_bbox(test_data, eval=True)
print('proposals shape:', preds_dict['proposals'].shape)
preds_dict['proposals']

Using matplotlib backend: Qt5Agg
proposals shape: torch.Size([2, 70400, 7])


tensor([[[ 2.1833e-01, -3.9804e+01, -1.0666e+00,  ...,  1.6960e+00,
           1.4719e+00, -1.6543e-01],
         [ 1.5326e-01, -3.9962e+01, -1.1290e+00,  ...,  1.6951e+00,
           1.5559e+00,  8.9931e-01],
         [ 2.8201e-01, -3.9423e+01, -1.0453e+00,  ...,  1.7556e+00,
           1.5455e+00, -8.8625e-03],
         ...,
         [ 7.0079e+01,  3.9359e+01, -8.6169e-01,  ...,  1.6644e+00,
           1.5330e+00, -7.1797e-01],
         [ 7.0216e+01,  3.9768e+01, -9.0181e-01,  ...,  1.6731e+00,
           1.5322e+00, -1.4505e+00],
         [ 7.0126e+01,  3.9930e+01, -9.3869e-01,  ...,  1.6767e+00,
           1.5150e+00,  4.6419e-02]],

        [[ 2.1833e-01, -3.9804e+01, -1.0666e+00,  ...,  1.6960e+00,
           1.4719e+00, -1.6543e-01],
         [ 1.5326e-01, -3.9962e+01, -1.1290e+00,  ...,  1.6951e+00,
           1.5559e+00,  8.9931e-01],
         [ 2.8201e-01, -3.9423e+01, -1.0453e+00,  ...,  1.7556e+00,
           1.5455e+00, -8.8625e-03],
         ...,
         [ 7.0090e+01,  3

In [6]:
print('proposals scores shape:', preds_dict['proposal_scores'].shape)
preds_dict['proposal_scores']

proposals scores shape: torch.Size([2, 70400, 2])


tensor([[[0.9004, 0.0996],
         [0.9460, 0.0540],
         [0.8976, 0.1024],
         ...,
         [0.9605, 0.0395],
         [0.9209, 0.0791],
         [0.9640, 0.0360]],

        [[0.9004, 0.0996],
         [0.9460, 0.0540],
         [0.8976, 0.1024],
         ...,
         [0.9558, 0.0442],
         [0.9128, 0.0872],
         [0.9599, 0.0401]]], device='cuda:0', grad_fn=<StackBackward>)

In [7]:
preds_dict['proposal_labels']

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]], device='cuda:0')

In [8]:
from kitti.io.kitti_io import KittiIo
file_reader = KittiIo(root="/home/ph/Dataset/KITTI/training")
for i in range(2):
    pos_mask = preds_dict['proposal_scores'][i,:,1] > 0.75
    bbox = preds_dict['proposals'][i, pos_mask]
    mask = test_data['points'][:, 0] == i
    w = VisualWindow(mode='3d', file_reader=file_reader)
    w.draw_point_cloud(test_data['points'][mask][:, 1:].cpu())
    w.draw_boxes3d(test_data['gt_boxes'][...,:-1][i].cpu().numpy(), 'corner')
    w.draw_boxes3d(bbox.cpu().detach().numpy(), 'corner', c='r')

# Post Process

## NMS

In [9]:
from basic.model.detect_model_base import Detect3DBase
from basic.utils.nms_utils import NMS3D
nms = NMS3D(nms_cfg=top_cfg.INFERENCE_CONFIG.POST_PROCESSING.NMS_CONFIG,
            scores_thresh=0.75)

In [10]:
nms_ret = nms.single_class_nms(cls_scores=preds_dict['proposal_scores'][..., -1],bbox_preds=preds_dict['proposals'])

In [13]:
for i in range(2):
    mask = nms_ret[:, 0] == i
    bbox = nms_ret[mask, 1:-1]
    scores = nms_ret[mask, -1]
    print(scores)
    mask = test_data['points'][:, 0] == i
    w = VisualWindow(mode='3d', file_reader=file_reader)
    w.draw_point_cloud(test_data['points'][mask][:, 1:].cpu())
    w.draw_boxes3d(test_data['gt_boxes'][...,:-1][i].cpu().numpy(), 'corner')
    w.draw_boxes3d(bbox.cpu().detach().numpy(), 'corner', c='r')

tensor([0.8726, 0.8637, 0.8469, 0.8400, 0.8297, 0.8183, 0.7993, 0.7805, 0.7718,
        0.7696, 0.7625, 0.7556], device='cuda:0', grad_fn=<IndexBackward>)
tensor([0.8940, 0.8490, 0.8449, 0.8432, 0.8076, 0.7900, 0.7842, 0.7819, 0.7775,
        0.7650], device='cuda:0', grad_fn=<IndexBackward>)
